Add support for firebase/php-jwt at version 6
imbo/behat-api-extension pull request #121
Opened 2022-08-23 09:36 UTC by pixelfantasy

As the firebase/php-jwt has an active vulnerability with a CVSS score of 7.5 (high) for every version below 6, there should be the possibility to upgrade that package. I made it optional to give the opportunity for other to adapt their code, if any dependencies are present.

Details of vulnerability can be found here:
https://security.snyk.io/vuln/SNYK-PHP-FIREBASEPHPJWT-2434829

2022-08-27 10:00 UTC, christeredvartsen requested changes
Please remove the change in the `.gitignore` file from the PR. It does not belong in the library.

2022-09-01 07:44 UTC, pixelfantasy commented
Hello Christer,

I set back the content of the .gitignore to the former state.

Greetings, Klaus

2022-09-08 06:18 UTC, christeredvartsen commented
The build is still failing.

2022-09-19 08:42 UTC, pixelfantasy commented
Local run of `composer validate --strict` was successful. Pushed changes to main on forked repo.

2022-09-26 11:13 UTC, jawira commented
@pixelfantasy You also have to update unit tests, simply changing `composer.json` is not enough.

2022-09-26 17:10 UTC, pixelfantasy commented
Sorry guys, 

but did not manage to fix the unit tests. The new Firebase JWT now demands a kid (Key ID) which is used to locate the secret. The kid node must be part of the header information. The tests consist of many comparisons which involve pregenerated JWT tokens. I tried to refactor the tests by adjusting the arrays and regenerate the jwt tokens with the help of https://jwt.io, but could not get it running. 

Honestly I am not so deep into this thematics and maybe somebody else has to take over at this point.

Primary involved files:
tests/ArrayContainsComparator/Matcher/JWTTest.php
src/ArrayContainsComparator/Matcher/JWT.php
vendor/firebase/php-jwt/src/JWT.php (functions decode() and later on getKey() which throws exception)

Information about kid:
https://stackoverflow.com/questions/37408684/is-it-still-possible-to-do-server-side-verification-of-tokens-in-firebase-3?noredirect=1#comment62518682_37408684

Resource for valid kid:
https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com

2022-11-29 13:55 UTC, khiminrm commented
Hi, any updates there? Can the maintainers of the library to fix the issue? I've also faced with it one project, where I need to upgrade firebase/php-jwt, but can't due the issue :(

2023-02-20 15:56 UTC, syl20b commented
Hi there,
Have you any news about this issue ? 
Thank you

2023-03-13 10:51 UTC, christeredvartsen commented
#125

2023-03-13 10:51 UTC, closed without merging